#!/bin/sh
set -e
# Automatically added by dh_pycentral
rm -f /var/lib/pycentral/sugar-etoys-activity.pkgremove
if which pycentral >/dev/null 2>&1; then
	pycentral pkginstall sugar-etoys-activity
	if grep -qs '^sugar-etoys-activity$' /var/lib/pycentral/delayed-pkgs; then
		sed -i '/^sugar-etoys-activity$/d' /var/lib/pycentral/delayed-pkgs
	fi
fi
# End automatically added section
